### PR TITLE
Descriptor added to issue, transfer and redeem

### PR DESCRIPTION
**Pull request by klorenzanaDG**
Descriptor has been added in the IssueSila, TransferSila and RedeemSila methods.
Version updated for guzzlehttp/guzzle to 6.5.4
Unit testing and Integration testing updated.
SDK version updated to 0.2.8-rc.
Readme updated

### CODE REVIEW

**Comment by ArcGate-Satyendra** [comment]
LGTM :+1:

**Comment by ArcGate-Satyendra** [comment]
@chepix10 @klorenzanaDG User Register method has Args mismatch error on readme. Please find more details on the attached screenshot. 
Sila_Money_Sila_PHP_SDK_User_Register_Wrong_Sequance

**Comment by chepix10** [comment]
@ArcGate-Satyendra Thanks for catching that one. I've fixed the documentation.

**Comment by isaacavery** [comment]
This work was merged into 0.2.8-rc.

**Pull request closed without merging**
